### ISSUE TITLE
cosine_similarities = linear_kernel(tfidf_matrix, tfidf_matrix) | FREEZING

### ISSUE THREAD

**Issue by maeckha** [jaganlal/content-based-recommender#1]
Hi jaganlal,

I´m following the same tutorial for a content-based recommender and am facing the exact same issue you described on [stackexchange](https://ai.stackexchange.com/questions/17821/code-freezes-and-never-returns-when-linear-kernel-sklearn-metrics-pairwise-is) and in your readme. 
First of all, I am glad not to be the only one facing this one. Did you manage to find a solution for this? For example did you find a workaround?
The tutorial on [datacamp](https://www.datacamp.com/community/tutorials/recommender-systems-python) mentions `cosine_similarities()` as possible alternative although linear_kernel() is supposed to be faster(?).

**Comment by jaganlal** [comment]
Hi @maeckha, i found the issue is due to the computing appetite that we have on our personal machines (PC/laptop/mac). Also i feel models like BERT, USE is far mature than basic tf-idf, so i moved out from this and opted other options. Checkout my repo [wiki-use-annoy](https://github.com/jaganlal/wiki-use-annoy)
